### ISSUE TITLE
NASAGIBS BlueMarble3413

### ISSUE THREAD

**Issue by davidbrochart** [geopandas/xyzservices#104]
In ipyleaflet we used to have a `NASAGIBS.BlueMarble3413` basemap, see e.g. [this notebook](https://github.com/jupyter-widgets/ipyleaflet/blob/caaddb8150e628f711fbfa2a11a29f70e9d84ef5/examples/CustomProjections.ipynb). I see xyzservices doesn't provide it, would it make sense to add it?

**Comment by martinfleis** [comment]
Yes, if you have its metadata just add them to the xyzservices-providers.json. See https://xyzservices.readthedocs.io/en/stable/contributing.html#providers

**Comment by davidbrochart** [comment]
Thanks, will do!
