### ISSUE TITLE
Add method to build full URL

### ISSUE THREAD

**Issue by darribas** [geopandas/xyzservices#13]
This would be in `lib` and would build the full URL, including tokens, etc. for a `TileProvider` object.

**Comment by jorisvandenbossche** [comment]
This is basically this code from contextily to move over? -> https://github.com/geopandas/contextily/blob/799c70802892f0276ace74159df3ed24779cedbf/contextily/tile.py#L292-L298

**Comment by martinfleis** [comment]
Yeah. Or this one from `geopandas_view` https://github.com/martinfleis/geopandas-view/blob/eea1c898e98413381086ad1a2c8b6005dfd357e7/geopandas_view/view.py#L275-L282

**Comment by jorisvandenbossche** [comment]
Ah, but that's slightly different: that's building the full url except with x/y/z/s still to be filled in, while the one I linked accepts x/y/z and already fills those in as well.

Probably the `s` (subdomain) should already be filled in, since that can depend on the Provider information?

**Comment by martinfleis** [comment]
> Probably the s (subdomain) should already be filled in, since that can depend on the Provider information?

That sounds right. I think we should be able to return both options, fully filled and and with xyz placeholders. Contextily can use the first version while folium the second.
