### ISSUE TITLE
BUG: package is broken for latest commit

### ISSUE THREAD

**Issue by m-richards** [geopandas/xyzservices#155]
https://github.com/geopandas/xyzservices/commit/6740b224e4187846a6069580e64621c6ce5127d4 seems to have broken xyzservices on import. I get this traceback running `pytest .` locally on main:
```python
xyzservices\__init__.py:2: in <module>
    from .providers import providers  # noqa
xyzservices\providers.py:15: in <module>
    providers = _load_json(json)
xyzservices\lib.py:600: in _load_json
    {i: TileProvider(provider[i]) for i in provider}
xyzservices\lib.py:600: in <dictcomp>
    {i: TileProvider(provider[i]) for i in provider}
xyzservices\lib.py:358: in __init__
    super().__init__(*args, **kwargs)
E   ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

or see https://github.com/geopandas/geopandas/actions/runs/7770406362/job/21190571888 downstream.

I'm not at all familiar with how xyzservices works, but from a quick glance it looks to me to do with the fact that the name "NLS" changed to "NLS.oslondon1k1893" and now that doesn't match with "NLS" in `BROKEN_PROVIDERS`?

(Also it doesn't seem like tests are running on CI - otherwise this would have shown up, I don't know if that's intentional or not)

**Comment by martinfleis** [comment]
Thanks for heads up. CI would've picked it up tomorrow while running as scheduled. I'll have a look what has happened in that automated update.
