### ISSUE TITLE
IGN (cx.providers.GeoportailFrance.orthos) migrated their services (wxs.ign.fr to data.geopf.fr)

### ISSUE THREAD

**Issue by salahelfarissi** [geopandas/xyzservices#165]
IGN just changed their routing this month (March 2024).
https://geoservices.ign.fr/services-geoplateforme-diffusion

```python
try:
    cx.add_basemap(
        m.ax,
        source=cx.providers.GeoportailFrance.orthos,
        attribution=True,
        crs=Maps.CRS.GOOGLE_MERCATOR,
        zoom=zoom_level,
    )
except HTTPError as e:
    logger.error("Failed to load basemap: %s", e)
    logger.warning("Continuing without basemap.")
```

**Comment by martinfleis** [comment]
Thanks for the report! It seems that our automatic tooling actually picked it up in https://github.com/geopandas/xyzservices/commit/f31e55732dd4cba65453af9a5ffa21e75a5dac63. I will cut a release of xyzservices tomorrow to get it out.

**Comment by martinfleis** [comment]
I was actually wrong, we the tooling needs to be migrated.

@HaudinFlorence would you be able to look at it? You did the original implementation.

**Comment by salahelfarissi** [comment]
I can work on it if it suits you.
I already work on a web platform that generates reports and we use their services.

![image](https://github.com/geopandas/xyzservices/assets/23387408/452f953f-ab0f-456f-bf96-2747826ab349)
![image](https://github.com/geopandas/xyzservices/assets/23387408/f07ddaf3-4879-4162-82f4-58e7c3194d55)

**Comment by martinfleis** [comment]
@salahelfarissi That would be very welcome. The code fetching the data currently lives here https://github.com/geopandas/xyzservices/blob/e8198dac0c10435c617dff3720aea3ec43561de4/provider_sources/_compress_providers.py#L87-L211

**Comment by HaudinFlorence** [comment]
@martinfleis I can have a look if needed. @salahelfarissi Please tell me if you need some help

**Comment by salahelfarissi** [comment]
@HaudinFlorence @martinfleis 
My first try. Please review and let me know if I need to write proper tests.
#166

**Comment by martinfleis** [comment]
@salahelfarissi it should be covered by existing test suite
