### ISSUE TITLE
Support scale_factor for Thunderforest

### ISSUE THREAD

**Issue by jorritsmit** [geopandas/xyzservices#173]
Hi,

According the to the [Thunderforest API](https://www.thunderforest.com/docs/map-tiles-api/) they support scaling in their url scheme. I checked and it works, so i wanted to make a PR to update the url in providers.json so scaling is supported. However, it seems these providers are automatically fetched from leaflet-providers. Should i make a PR there?

**Comment by martinfleis** [comment]
Yes. Thank you!

**Comment by jorritsmit** [comment]
PR made here https://github.com/leaflet-extras/leaflet-providers/pull/576
