### ISSUE TITLE
Hydda basemaps

### ISSUE THREAD

**Issue by davidbrochart** [geopandas/xyzservices#22]
We have been having issues with Hydda basemaps (at least Full and Base) for the last year or so, the server seems to be definitely down.
Looking at the [ipyleaflet documentation](https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html), MtbMap seems to be down too (and Strava but it is not listed in the providers here).

**Comment by martinfleis** [comment]
Thanks for the notice! Stadia seems to be down too (#20).

I want to write some tests for basemaps that do not require token so we should be able to catch non-functional ones automatically in the future.

**Comment by martinfleis** [comment]
@davidbrochart Hydda maps (and some other) are now marked with `TileProvider.status = "broken"` flag. All open providers (no API key) are now tested.

Closed by #78
