### ISSUE TITLE
Exclude broken sources from leaflet-providers

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#24]
We currently create `leaflet-providers-parsed.json` automatically but it comes with some providers which are not working anymore (e.g. #22). These should not be available in `xyzservices` but we should not manually delete them from the JSON because such a change would break with every update (which will be later automatised using GHA). 

We should find a clever way to mark broken resources and exclude them during compression of source files to the final one shipped with the package. One way could be a simple list of keys in `_compress_providers.py` (once #23 is in) which we can pop out of the dict. Might be the easiest one.

**Comment by benbovy** [comment]
Additionally or alternatively, is there any easy way to quickly test during runtime the status of a provider and get the results, e.g., via  `Bunch.status` and/or `TileProvider.status` properties?

I can imagine how this kind of information could be useful in downstream libraries for the UI (for example: in a selection widget grey out items for the basemaps that are not currently working). I'm not sure if it happens often that providers stop working temporarily, though.

**Comment by martinfleis** [comment]
@benbovy That is actually quite tricky to test because some providers restrict the access, so you can load it in leaflet but cannot download the tile itself (i.e. to be used in contextily). But I agree that it would be a nice thing to have.

**Comment by martinfleis** [comment]
Closed by #78 

@benbovy Broken providers are now marked manually based on the CI result. Those unavailable for some reason now have `TileProvider.status = "broken"`. Note that fully functional providers do not have a status attribute (I don't want to clutter the JSON).
