### ISSUE TITLE
Versioning model

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#26]
I was thinking about versioning and I'd suggest we adopt some version of [calendar versioning](https://calver.org) instead of [semantic versioning](https://semver.org) we use elsewhere. Because once stable, I assume that most of the releases will be just updates of available providers and putting a date on the release makes much more sense than a number.

I was thinking about following `dask` model with `YYYY.MM.MINOR`, so if we'd make a release now, it would be `2021.05.0`. 

In practice, we'll just need to use this schema when creating tags, nothing else.

**Comment by jorisvandenbossche** [comment]
+1 on using calendar versioning following dask's model for the exact version string

**Comment by darribas** [comment]
+1 on calendar too!
