### ISSUE TITLE
Add Esri World Dark Gray Canvas basemap

### ISSUE THREAD

**Issue by darribas** [geopandas/xyzservices#41]
Moving [`contextily#181`](https://github.com/geopandas/contextily/pull/181) over here to integrate it with community-contributed providers.

> Adds the Esri World Dark Gray Canvas basemap to the provider list.
>
> See:
> - https://www.arcgis.com/home/item.html?id=1970c1995b8f44749f4b9b6e81b5ba45
> - https://server.arcgisonline.com/arcgis/rest/services/Canvas/World_Dark_Gray_Base/MapServer

cc' @EwoutH

**Comment by EwoutH** [comment]
Thanks!

**Comment by darribas** [comment]
The link provided seems to be deprecated, this is the updated version:

https://www.arcgis.com/home/item.html?id=358ec1e175ea41c3bf5c68f0da11ae2b

**Comment by abubelinha** [comment]
Not sure if this is related, but I am interested in using some public tile providers which seems to use an ArcGIS WMTS server as described here:
https://developers.arcgis.com/rest/services-reference/enterprise/wmts-tile-image-service/

I think this would be an [example](https://ideg.xunta.gal/servizos/rest/services/Raster) of such servers. 
I know some of the services listed there are shown as tiled raster layers in their web map viewer.

So my question is how to use those layers in contextily ... if possible. 
I suspect those "WMTS tiles" are not following the same numbering system as contextily (just try-error of particular tile urls).
But I am a complete ignorant about how these services work. 
@darribas perhaps you know esri arcgis servers accept also some other url syntax so I can use them in contextily?

Thanks in advance
@abubelinha

**Comment by martinfleis** [comment]
@abubelinha you can check how we deal with Geoportail France tiles. I believe those are WMTS.

**Comment by abubelinha** [comment]
Thanks @martinfleis that was helpful

I think these are the urls informative about server capabilities:
- [Geoportail France](https://www.geoportail.gouv.fr/) (project https://rok4.github.io/):
   https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities
- [IDE-Galicia](https://mapas.xunta.gal/):
   https://ideg.xunta.gal/servizos/rest/services/MapasBase/MapaBase/MapServer/WMTS?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities

Too tech for me. 
Following [leaflet-providers-parsed.json](https://github.com/geopandas/xyzservices/blob/main/provider_sources/leaflet-providers-parsed.json) Geoportail France example urls, I was able to get tiles from both using querystring parameter syntax. But again, it seems that tile references are quite different for similar areas (1st one follows OSM, 2nd one does not):
- https://wmts.geopf.fr/wmts?layer=ORTHOIMAGERY.ORTHOPHOTOS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=8&TileCol=121&TileRow=94
- https://ideg.xunta.gal/servizos/rest/services/MapasBase/MapaBase/MapServer/WMTS?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=default&TILEMATRIXSET=default028mm&FORMAT=image/jpeg&LAYER=MapaBase&TILEMATRIX=3&TILEROW=33&TILECOL=35

I see the first one (France) has CRS entries like this: 
`<TileMatrixSet>...<ows:SupportedCRS>EPSG:3857</ows:SupportedCRS>...</TileMatrixSet>`

Whereas the 2nd one (NW Spain) has a different CRS support: 
`<TileMatrixSet>...<ows:SupportedCRS>urn:ogc:def:crs:EPSG::25829</ows:SupportedCRS>...</TileMatrixSet>`

May this be making it not compatible with contextily?

**Comment by martinfleis** [comment]
Contextily assumes EPSG:3857, which is the standard CRS for web tiles. I am not sure if you can make it work with EPSG 25829 without changes of the code.
