### ISSUE TITLE
HTML attribution

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#58]
We currently store attribution as a basic string only. I've noticed that interactive packages like `ipyleaflet` tend to add HTML links to OpenStreetMap and others. It might be good to add a support of `html_attribution` which would return HTML string with proper links.

**Comment by darribas** [comment]
This is a good idea. If nothing else is available (I think some providers do suggest HTML), we could have a `build_html_attribution` method with a simple yet stylish version?

**Comment by jorisvandenbossche** [comment]
For the leaflet provider sources, the original actually has html attribution, which currently gets converted to plain text (for simple usage with matplotlib):

https://github.com/geopandas/xyzservices/blob/ee5ade0745103a73ae5f587b47c505348288d246/provider_sources/_parse_leaflet_providers.py#L123-L126

So for those sources it should be easy to keep both in the parsed data.
