### ISSUE TITLE
Gallery of tiles

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#61]
It would be nice to have a gallery similar to https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html. It can be used to check tiles (xref #59) and would provide a nice overview to users. Ideally automatically generated.

**Comment by giswqs** [comment]
Leafmap has a [linked_maps](
https://leafmap.org/notebooks/11_linked_maps) function that can be helpful for creating the basemap gallery. 


![linked_maps](https://user-images.githubusercontent.com/5016453/128360880-df071619-d02d-486d-a733-6173760cf34a.gif)

**Comment by giswqs** [comment]
I just added a gallery of basemaps in leafmap. 

Try it out: https://gishub.org/basemap-gallery
Notebook: https://github.com/giswqs/leafmap/blob/master/examples/notebooks/27_basemap_gallery.ipynb

https://user-images.githubusercontent.com/5016453/128373240-4e0625d9-261e-4f4a-b5bf-a5e044d3c8dd.mp4

**Comment by martinfleis** [comment]
That is so cool 🤩! I have to admit that it is a bit too heavy for my laptop to play with it :).

**Comment by giswqs** [comment]
Yeah, it can take a while to load. There are 200+ basemaps available, and that example only uses 100. You can easily specify the number of basemaps to show in the gallery.

**Comment by HaudinFlorence** [comment]
I am currently working on producing a webpage showing a gallery of the basemaps from the .json file (a PR will be soon submitted). Here is a screenshot of the current state of my work.

![leaflet_catalog_screenshot](https://user-images.githubusercontent.com/99649086/157486878-708f9318-aa7b-4ee7-8e05-96dc4c5b1da6.png)

**Comment by martinfleis** [comment]
@HaudinFlorence Very nice! If we could plug this in out sphinx-generated docs, that would be amazing!

**Comment by HaudinFlorence** [comment]
It seems that Hydda and HikeBike's basemaps are not available anymore. I also did not manage to display some of HERE's basemaps : both an app_id and an app_code are required but some of the basemaps can be displayed without any code. For the other ones, I can't displayed them. As a question, are basemaps from HERE and HEREv3 really different? At first sight they are looking rather similar.

**Comment by martinfleis** [comment]
Just skip them. Hydda is known to be broken, but it was supposed to be temporary breakage. HERE are the same, just the API is different if I remember correctly.

**Comment by martinfleis** [comment]
Closed by #114
