### ISSUE TITLE
Add Google basemaps 

### ISSUE THREAD

**Issue by giswqs** [geopandas/xyzservices#63]
It would be great to add Google basemaps to `providers.json`. 

- Google Roadmap: https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}
- Google Terrain: https://mt1.google.com/vt/lyrs=p&x={x}&y={y}&z={z}
- Google Satellite: https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}
- Google Hybrid: https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}

**Comment by martinfleis** [comment]
That would be a welcome contribution! Would you like to make a PR? I would add them as a single `Bunch`.

New providers should be added to https://github.com/geopandas/xyzservices/blob/main/provider_sources/xyzservices-providers.json. See the contributing docs https://xyzservices.readthedocs.io/en/latest/contributing.html#providers

**Comment by giswqs** [comment]
I will work on it and submit a PR later today.

**Comment by martinfleis** [comment]
Actually, can you ensure we can legally use those? I am not entirely sure about that based on https://developers.google.com/maps/faq#tos_tiles.

**Comment by giswqs** [comment]
This is interesting to know. I didn't realize that. I have been using these map tiles for years through the QGIS QuickMapServices Plugin. I am not sure how this plug handles the legal issues.

- https://plugins.qgis.org/plugins/quick_map_services
- https://qms.nextgis.com

**Comment by martinfleis** [comment]
It seems that they just don't care. 

I was wondering such an obvious source is not already included. See https://github.com/leaflet-extras/leaflet-providers/issues/236, https://github.com/leaflet-extras/leaflet-providers/issues/288, and https://github.com/leaflet-extras/leaflet-providers/issues/22 as a reference. 

Strictly speaking, we are not _using_ those tiles, just providing their metadata so we wouldn't violate TOS if we included them. But anyone who would use them from `xyzservices` would if I understand correctly. A bit of a grey zone here (but I think that `leafmap` does violate it).

**Comment by giswqs** [comment]
Thanks for linking these references. I agree it is a grey area. I will change leafmap's default basemap to other free tiles rather than Google Maps. 

So, do we still want to include their metadata in `xyzservices`? I can submit a PR if you want. If not, we can close this issue.

**Comment by giswqs** [comment]
I have changed leafmap's default basemap from Google Maps to OpenStreetMap, but I keep the metadata of Google map tiles for users who want to use them at their own risk. If Google comes after me, I will then remove them. 
https://github.com/giswqs/leafmap/issues/91

![image](https://user-images.githubusercontent.com/5016453/128111932-d4caa9ec-1a05-402a-a7be-ef491f154a52.png)

**Comment by martinfleis** [comment]
@giswqs With #65 there is a convenient way of getting Google's base maps as a `TileProvider`, so I suggest closing this issue and not including them directly in our JSON. Would it be okay with you? With your https://github.com/giswqs/leafmap/issues/92 you can pass Google Hybrid to leafmap as

```py
basemap = xyzservices.TileProvider.from_qms("Google Satellite Hybrid")
m = leafmap.Map()
m.add_basemap(basemap)
```

**Comment by giswqs** [comment]
Yes, this is a much better solution. Thank you.
