### ISSUE TITLE
ENH: add `flatten` method on `Bunch`

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#67]
> It would be great if xyzservices can add a function that returns a non-nested dictionary of all tiles, similar to the get_xyz_dict function I implemented in leafmap. My implementation is probably not optimal.  https://github.com/giswqs/leafmap/blob/master/leafmap/basemaps.py#L206

_From @giswqs  https://twitter.com/giswqs/status/1423265380236201984_

---
I guess that a method `Bunch.flatten()` returning a flat dict would be a good one. Thanks for the suggestion!

**Comment by martinfleis** [comment]
@giswqs regarding keywords filtering providers, I'd wait for #42. Then the API mirroring your `free_only=True` keyword would be `xyz.filter(requires_token=False).flatten()`.

**Comment by giswqs** [comment]
Awesome! This will make it much easier to pass the list of tiles to the leafmap basemap GUI.
