### ISSUE TITLE
Tests are installed incorrectly

### ISSUE THREAD

**Issue by QuLogic** [geopandas/xyzservices#96]
The sdist correctly includes tests. However, if you build and install from the sdist, the tests are installed in `.../site-packages/tests/`. This is at the top-level and the wrong place for such a generic package name. If installed, they should be in the `xyzservices` directory, but probably you don't want to be installing them at all.

**Comment by martinfleis** [comment]
Do you have any idea why is that and how to fix it?

**Comment by QuLogic** [comment]
`find_packages` finds everything with `__init__.py`, and `tests` has one. You need to pass `exclude=['tests']` to ignore it (and possibly add an entry in `MANIFEST.in` now so that the sdist continues to get tests.)

**Comment by martinfleis** [comment]
Closed by #97
