### ISSUE TITLE
Add Official Switzerland provider wmts Geo.Admin.ch

### ISSUE THREAD

**Issue by davidoesch** [geopandas/xyzservices#99]
Via Geo.Admin.ch a WMTS which is Opendata can be used to be added as provider 
https://api3.geo.admin.ch/services/sdiservices.html#wmts

Glad to help if needed

**Comment by martinfleis** [comment]
Hi, we have moved the issue from contextily here as this is where providers live. On your suggestion - at the moment, we support only XYZ standard, not WMTS. There has been a discussion on that and it is on a wish list to support more tile formats but I can't tell when that is going to happen. If Geo.Admin.ch support XYZ standard, I am happy to add it. Or you can do it yourself following this guide: https://xyzservices.readthedocs.io/en/stable/contributing.html#providers

**Comment by davidoesch** [comment]
hi @procrastinatio can you add the XYZ template based on our wmrts GetCapabilities ? AFAIK contextily runs on Webmercator as well so it should work...

**Comment by martinfleis** [comment]
>  AFAIK contextily runs on Webmercator as well so it should work...

Yes, it is assumed that all tiles come in web mercator (EPSG:3857).

**Comment by martinfleis** [comment]
Closed by #100
